cask_args appdir: '/Applications'

tap "google-chrome"
tap "adoptopenjdk/openjdk"
tap "aws/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "sanemat/font"
brew "awscli"
brew "harfbuzz"
brew "ffmpeg"
brew "fontforge"
brew "iceberg"
brew "git"
brew "jq"
brew "docker"
brew "docker-machine"
brew "mkcert"
brew "postgresql"
brew "wget"
brew "tree"
brew "nodebrew"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "sanemat/font/ricty"
cask "soundflower"
cask "bettertouchtool"
cask "zoom"
cask "flux"
cask "iterm2"
cask "vlc"
cask "slack"
cask "visual-studio-code"
cask "karabiner-elements"
cask "messenger"
cask "rectangle"
cask "tableplus"
cask "notion"
cask "contexts"
cask "the-unarchiver"
cask "cleanmymac"
cask "app-cleaner"
cask "google-japanese-ime"
cask "deepl"
cask "docker"
cask "alfred"
cask "google-cloud-sdk"
cask "michaelvillar-timer"
cask "ngrok"

mas "Display menu", id: 549083868
mas "Amphetamine", id: 937984704
mas "RunCat", id: 1429033973
mas "Reeder 5", id: 1529448980
